---
title: "CWE-584: Return Inside Finally Block"
---

## Description
The code has a return statement inside a finally block, which will cause any thrown exception in the try block to be discarded.

## Extended Description
None

## Likelihood of Exploit
None

## Background Detail
None
        